const products = [
    {
      id: 1,
      name: "Marvel theme T-shirt",
      image: "/src/assets/marvel/1.avif",
      price: 6000,
      category: "marvel",
      company: "apple",
      color: "black",
    },
    {
      id: 2,
      name: "Dc logo T-shirt",
      image: "/src/assets/Dc/1.avif",
      price: 5000,
      category: "Dc",
      company: "samsung",
      color: "blue",
    },
    {
      id: 3,
      name: "Jutjutsu Kaisen T-shirt",
      image: "/src/assets/anime/1.jpg",
      price: 6000,
      category: "anime",
      company: "dell",
      color: "gray",
    },
    {
      id: 4,
      name: "Call Of Duty MW2 T-shirt",
      image: "/src/assets/gaming/5.jpg",
      price: 429,
      category: "gaming",
      company: "apple",
      color: "gray",
    },
    {
      id: 5,
      name: "Marvel Venom T-shirt",
      image: "/src/assets/marvel/2.webp",
      price: 9000,
      category: "marvel",
      company: "apple",
      color: "black",
    },
    {
      id: 6,
      name: "PUBG T-shirt",
      image: "/src/assets/gaming/2.png",
      price: 8000,
      category: "gaming",
      company: "apple",
      color: "black",
    }, 
    {
      id: 7,
      name: "Watch Series",
      image: "/src/assets/marvel/3.webp",
      price: 7000,
      category: "watch",
      company: "apple",
      color: "black",
    },
    {
      id: 8,
      name: "Watch Series",
      image: "/images/watch.jpg",
      price: 4000,
      category: "watch",
      company: "apple",
      color: "black",
    }, 
    {
      id: 9,
      name: "Watch Series",
      image: "/images/watch.jpg",
      price: 2000,
      category: "watch",
      company: "apple",
      color: "black",
    },
    {
      id: 10,
      name: "Watch Series",
      image: "/images/watch.jpg",
      price: 2000,
      category: "watch",
      company: "apple",
      color: "black",
    },
    {
      id: 11,
      name: "Watch Series",
      image: "/images/watch.jpg",
      price: 4000,
      category: "watch",
      company: "apple",
      color: "black",
    },
    {
      id: 12,
      name: "Watch Series",
      image: "/images/watch.jpg",
      price: 3000,
      category: "watch",
      company: "apple",
      color: "black",
    },
    {
      id: 13,
      name: "Watch Series",
      image: "/images/watch.jpg",
      price: 9000,
      category: "watch",
      company: "apple",
      color: "black",
    },
    {
      id: 14,
      name: "Watch Series",
      image: "/images/watch.jpg",
      price: 3000,
      category: "watch",
      company: "apple",
      color: "black",
    },
    {
      id: 15,
      name: "Watch Series",
      image: "/images/watch.jpg",
      price: 4000,
      category: "watch",
      company: "apple",
      color: "black",
    },
  ];
  
  export default products;